---

# Run ansible-playbook brew.yml --connection=local --inventory 127.0.0.1,

- name: Ensure gccjit is enabled
  hosts: all
  tasks:
    - name: Add gccjit
      lineinfile:
        path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
        regexp: 'languages ='
        line: '    languages = %w[c c++ objc obj-c++ fortran jit]'
    - name: Enable host shared
      lineinfile:
        path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
        # regexp: 'args = %W\['
        insertafter: 'args = %W\['
        line: '      --enable-host-shared'


- name: Install homebrew packages
  hosts: all
  tasks:
    - name: Add binary dependencies
      homebrew:
        name: gnutls,giflib,libtiff,jpeg
    - name: Add gcc as a compiled dependency
      homebrew:
        name: gcc
        install_options: build-from-source
